This project has multiple parts. Please write the code below the project description. Grading follows tha same rubric posted for Project 1. 

### Part 1
Write a Python function, ``make_array`` for generate and return a random Numpy array filled with random integers. This function can accpet the following arguments:
- length: the default value of this argument is 100
- seed: the seed value for the Numpy randomization. the default value should be 0

In [30]:
import numpy as np
def make_array(l=100,seed=0):
    np.random.seed(seed)
    value=np.random.randint(1,100,l)
    return value
print('random array is:\n',make_array(20,30))

random array is:
 [38 38 46 46 13 24  3 54 18 47  4 42  8 66 50 46 62 36 19 19]


### Part 2
Write a Python function, ``make_2d_array`` that return a Numpy array of integer tuples. This function accets two Numpy arrays as input. If the length of two input arrays does not match, the shorter array will be filled with extra zeros at the end of the array. Then Concatenate these arrays to return a 2d Numpy array. 

In [31]:
def make_2d_array(l1 , l2):
    if len(l1) != len(l2):
        if len(l1) > len(l2):
            l3 = len(l1) - len(l2)
            for zeros in range(l3):
                l2.append(0)
        elif len(l1) < len(l2):
            l3 = len(l2) - len(l1)
            for zeros in range(l3):
                l1.append(0)
        a = np.concatenate((l1, l2))
        a1 = np.reshape(a, (2, len(l1)))
        
        return a1
    else:
        a = np.concatenate((l1, l2))
        a1 = np.reshape(a, (2, len(l1)))
        
        return a1
        
x = [1,2,3,4,5,6,7,8]
y = [9,10,11]

z = make_2d_array(x , y)
print('2D Numpy array is:\n',z)


2D array is:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11  0  0  0  0  0]]


### Part 3
Write a Python function ``replace_zero`` to replace zeros in each columns with a random integer between 1 and maximum of positive values in the same column. For example if the values in a column are 5, 0, and 8, replace zero with a random integer between 1 and 8 (including both 1 and 8). This function will accept a 2d Numpy array and a Numpy seed as an input and returns the modified 2d Numpy array as output.  

Note: if all the values in a column are zero, replace all zeros with 1. 

In [32]:
def replace_zero(l2d):
    for column in l2d.T:
        low = 1
        high = 0
        for i in column:
            if i > high:
                high = i
        l = 0
        if high == 0:
            l2 = 0
            for i in column:
                column[l2] = 1
                l2 = l2+1
        else:
            for i in column:
                new = np.random.randint(low, high)
                if i == 0:
                    column[l] = new
                l = l+1
    return l2d
print('replaced 2d array is:\n',replace_zero(z))


replaced 2d array is:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11  1  3  5  3  7]]
